import java.util.Scanner; // ...

/**
 * Write a description of class Rectangle here.
 * ...
 * 
 */
public class Rectangle
{
    double length; // ...
    double width; // ...

    /*
     * 
     */
    public Rectangle(double l, double w)
    {
        length = l; // ...
        width = w;  // ...
    }

    
    /*
     * This method ... 
     */
    public double getLength() {
        return length; // ...
    }
    
    /*
     * This method ...
     */
    public double getWidth() {
        return width; // ...
    }
    
    /*
     * This method ...
     */
    public boolean isSquare()
    {
        return (length == width); // ...
    }
    
    /*
     * This method ...
     */
    public double getArea() {
        double area = length * width; // ...
        return area; // ...
    }
    
    /*
     * This method ...
     */
    public double getPerimeter() {
        return 2 * (length + width); // ...
    }
    
    /*
     * The main method ...
     */
    public static void main(String[] args) {
        Scanner keyboard = new Scanner(System.in); // ...
        
        String cont = "yes"; //...
        
        /*
         * The following do-while block...
         */
        do {
            /*
             * The next 4 lines ...
             */
            System.out.print("Please enter the rectangle length: ");
            double len = keyboard.nextDouble(); // ...
            System.out.print("Please enter the rectangle width: ");
            double wid = keyboard.nextDouble(); // ...
            
            /*
             * The if statement and the next 4 lines ...
             */
            if ((len <= 0) || (wid <= 0)) { // ...
                System.out.println("Sorry you entered a negative value. Please try again.\n");
                continue;  // ...
            }
            
            Rectangle myRectangle = new Rectangle(len, wid); // ...

            // ...
            System.out.println("The length of the rectangle is " + myRectangle.getLength()); 
            
            // ...
            System.out.println("The width of the rectangle is " + myRectangle.getWidth());
            
            // ...
            System.out.println("The area of the rectangle is " + myRectangle.getArea());
            
            // ...
            System.out.println("The perimeter of the rectangle is " + myRectangle.getPerimeter());
                        
            boolean isSquare = myRectangle.isSquare(); // ...
            
            /*
             * The following if-else statement ...
             */
            if (isSquare) { // ...
                System.out.println("The rectangle is a square."); // ...
            }
            else { // ...
                System.out.println("The rectangle is no square."); // ...
            }
            
            System.out.print("Do you want to continue [yes/no]? "); // ...
            cont = keyboard.next(); // ...
            System.out.println(""); // ...
        }
        while (cont.equals("yes")); // ...
        
        System.out.println("Goodbye!"); // ...
    }
}
